### ISSUE TITLE
"grep -p" Seems to be a Invalid Option

### ISSUE THREAD

**Issue by sparkcyf** [NewbieOrange/SUSTech-EnetLogin#2]
When i run this script, it returns: 
**"grep: unrecognized option: P"**

Somebody have the similar issue here:
https://github.com/firehol/firehol/issues/325

**Comment by NewbieOrange** [comment]
Please use GUN grep, or install pcregrep for perl regex support.

Other implementations of grep may not support perl regex correctly.

**Comment by pablorsk** [comment]
This is a problem with BusyBox multi-call binary.

Please, add `grep` package. This is one way to do: 

```bash
apk add --no-cache grep
```
